### ISSUE TITLE
Result.Error returns null instead of Result when returned from a method called from a controller

### ISSUE THREAD

**Issue by selaromdotnet** [ardalis/Result#186]
I'm having the weirdest issue, and I'm sure I'm probably just setting this up or using it wrong, but I can't figure out what that is.

I created a controller that I want to use to call a service that returns a result. If the result is successful, I get that result just fine. However if the service fails for whatever reason, and I attempt to return an error, that error result is null instead.

I created a super simple solution that mimics what I'm doing and does demonstrate the described behavior here: https://1drv.ms/u/s!Ahj4lgIVz2Ld6qwyH38Csz1FKpGY0g?e=p9Ac2D

It's just a controller with an injected service that returns one of the two results. The Success result works, but the Error result throws a null reference exception back in the calling controller because null is returned instead.

What am I doing wrong? this weirdly seems to work in other spots using razor pages, so I think maybe there's something wrong with my controller context or setup?

Any ideas? Much appreciated!!

**Comment by selaromdotnet** [comment]
huh, interesting, this is now breaking in the razor pages too, where it wasn't before.. the only thing different i can think of is VS just updated for the latest release announced at build yesterday. perhaps that broke something, anybody else able to reproduce/not reproduce this issue care to share their vs version?

**Comment by ibrhmklc** [comment]
I just added this package to my project. In my first tests, I got a null error when I wanted to return the Error class. There are no problems with other return types. However, when returning with Error, a null result is returned to the person calling the method.

**Comment by GiampaoloGabba** [comment]
I can confirm this.
When i return `Result.Error` or `Result.CriticalError` from a method and then i to ` .ToMinimalApiResult ` i get a `NullReferenceException`. and the API breaks.

Trying to debug the issue, the result input parameter is null:

![image](https://github.com/ardalis/Result/assets/8319337/eba75470-88f0-41a9-8f99-1cc03e20bc95)

But the problem is not only in ` .ToMinimalApiResult ` , is the whole Result.Error problematic. If return a Result.Error from a method and try to access it i get a nullrefrenceException no matter what

**Comment by selaromdotnet** [comment]
[celebrate]     Josh Morales reacted to your message:
________________________________

**Comment by ardalis** [comment]
It's live!
https://www.nuget.org/packages/Ardalis.Result
