### ISSUE TITLE
List<ValidationError>should be also in Error function?

### ISSUE THREAD

**Issue by ShadyNagy** [ardalis/Result#43]
@ardalis 
What do you think?
If you agree I will make PR

```csharp
public static Ardalis.Result.Result<T> Error(params string[] errorMessages)
```
to 
```csharp
public static Ardalis.Result.Result<T> Error(List<ValidationError> validationErrors)
```

**Comment by ardalis** [comment]
This is by design; the errorMessages collection is meant to be a high level description of an error, probably coming from an exception. It could be anything - database constraint, network error, business logic - and not dependent on a particular property or parameter being validated, like ValidationError expects.
